apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-preview-stakater-nordmart-reivew-web
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: retail
    stakater.com/env: preview
    stakater.com/kind: preview
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    namespace: retail-build
    server: 'https://kubernetes.default.svc'
  project: retail
  source:
    path: retail/review-web/preview
    repoURL: 'https://github.com/DESTINATION_ORG/apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
