apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-dev-stakater-nordmart-reivew-api
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: retail
    stakater.com/env: dev
    stakater.com/kind: dev    
spec:
  destination:
    namespace: retail-dev
    server: 'https://kubernetes.default.svc'
  project: retail
  source:
    path: retail/review-api/dev
    repoURL: 'https://github.com/DESTINATION_ORG/apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true