apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-build
  namespace: rh-openshift-gitops-instance
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: retail
  source:
    path: retail/argocd-apps/build
    repoURL: 'https://github.com/DESTINATION_ORG/apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
